name: JS Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup mamba
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Create the conda environment
      run: mamba install -q python=3.9 pip>17

    - name: Install dependencies
      run: |
        python --version
        node --version

        python -m pip install --upgrade -e ".[test]"

    - name: Run tests
      run: |
        yarn run test:ci

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
